<!DOCTYPE html>
<html class="no-js" lang="en-us">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Corona Shiny Project 6_1 - 데이터 전처리 - Data Science | ChloEvan</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
	<meta property="og:title" content="Corona Shiny Project 6_1 - 데이터 전처리" />
<meta property="og:description" content="공지 이번에 준비한 튜토리얼은 제 강의를 듣는 과거-현재-미래 수강생분들을 위해 준비한 자료이다. 많은 도움이 되기를 바란다
이번에 준비한 Tutorial 코로나 세계현황을 Shiny Dashboard로 만들어 가는 과정을 담았다.
I. Shiny Tutorial 소개 처음 shiny를 접하거나 shiny의 전체 튜토리얼이 궁금한 사람들을 위해 이전 글을 소개한다.
 shiny tutorial 01 - get started shiny tutorial 02 - Shiny Structure shiny tutorial 03 - HTML content shiny tutorial 04 - Shiny Layouts shiny tutorial 05 - Sharing Apps shiny tutorial 06 - shinydashboard shiny tutorial 07 - flexdashboard shiny tutorial 08 - HTML, CSS 적용  II." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://chloevan.github.io/r/shiny/project_06_01/" />
<meta property="article:published_time" content="2020-04-14T10:15:39+09:00" />
<meta property="article:modified_time" content="2020-04-14T10:15:39+09:00" />

	<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Corona Shiny Project 6_1 - 데이터 전처리"/>
<meta name="twitter:description" content="공지 이번에 준비한 튜토리얼은 제 강의를 듣는 과거-현재-미래 수강생분들을 위해 준비한 자료이다. 많은 도움이 되기를 바란다
이번에 준비한 Tutorial 코로나 세계현황을 Shiny Dashboard로 만들어 가는 과정을 담았다.
I. Shiny Tutorial 소개 처음 shiny를 접하거나 shiny의 전체 튜토리얼이 궁금한 사람들을 위해 이전 글을 소개한다.
 shiny tutorial 01 - get started shiny tutorial 02 - Shiny Structure shiny tutorial 03 - HTML content shiny tutorial 04 - Shiny Layouts shiny tutorial 05 - Sharing Apps shiny tutorial 06 - shinydashboard shiny tutorial 07 - flexdashboard shiny tutorial 08 - HTML, CSS 적용  II."/>

	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">
	<link rel="stylesheet" href="/css/style.css">
	<link rel="stylesheet" href="/css/custom.css">
	<link rel="shortcut icon" href="/favicon.ico">
		
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-160625195-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

	<meta name="naver-site-verification" content="589373cb2d4668f329792265c1fdbec3a72ec17d" />
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container">
		<div class="logo">
			<a class="logo__link" href="/" title="Data Science | ChloEvan" rel="home">
				<div class="logo__title">Data Science | ChloEvan</div>
				<div class="logo__tagline">Love your beloved one forever</div>
			</a>
		</div>
		
<nav class="menu">
	<button class="menu__btn" aria-haspopup="true" aria-expanded="false" tabindex="0">
		<span class="menu__btn-title" tabindex="-1">Menu</span>
	</button>
	<ul class="menu__list">
		<li class="menu__item">
			<a class="menu__link" href="/ds-projects/">
				
				<span class="menu__text">DS-Projects</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/gcp/">
				
				<span class="menu__text">GCP</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/kaggle/">
				
				<span class="menu__text">Kaggle</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/python/">
				
				<span class="menu__text">Python</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/r/">
				
				<span class="menu__text">R</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/settings/">
				
				<span class="menu__text">settings</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/about/">
				
				<span class="menu__text">About ChloEvan</span>
				
			</a>
		</li>
	</ul>
</nav>

	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Corona Shiny Project 6_1 - 데이터 전처리</h1>
			<div class="post__meta meta">
<div class="meta__item-datetime meta__item">
	<svg class="meta__icon icon icon-time" width="16" height="14" viewBox="0 0 30 28"><path d="M15 0C7 0 1 6 1 14s6 14 14 14 14-6 14-14S23 0 15 0zm0 25C9 25 4 20 4 14S9 3 15 3s11 5 11 11-5 11-11 11zm1-18h-2v8.4l6.8 4.4L22 18l-6-3.8V7z"/></svg>
	<time class="meta__text" datetime="2020-04-14T10:15:39&#43;09:00">2020-04-14</time>
</div>

<div class="meta__item-categories meta__item">
	<svg class="meta__icon icon icon-category" width="16" height="16" viewBox="0 0 16 16"><path d="m7 2l1 2h8v11h-16v-13z"/></svg>
	<span class="meta__text"><a class="meta__link" href="/categories/development/" rel="category">Development</a>, <a class="meta__link" href="/categories/r/" rel="category">R</a>, <a class="meta__link" href="/categories/shiny/" rel="category">Shiny</a>, <a class="meta__link" href="/categories/corona-shiny-app/" rel="category">Corona Shiny App</a>
	</span>
</div></div>
		</header>
<div class="post__toc toc">
	<div class="toc__title">Page content</div>
	<div class="toc__menu">
		<nav id="TableOfContents">
  <ul>
    <li><a href="#공지">공지</a></li>
    <li><a href="#i-shiny-tutorial-소개">I. Shiny Tutorial 소개</a></li>
    <li><a href="#ii-shiny-project">II. Shiny Project</a></li>
    <li><a href="#iii-생각해볼-문제">III. 생각해볼 문제</a></li>
    <li><a href="#iv-데이터-처리의-문제점">IV. 데이터 처리의 문제점</a></li>
    <li><a href="#1-지도-데이터셋에-포함된-국가의-숫자">(1) 지도 데이터셋에 포함된 국가의 숫자</a></li>
    <li><a href="#2-corona-데이터셋-국가의-숫자">(2) corona 데이터셋 국가의 숫자</a></li>
    <li><a href="#3-동일-국가이나-기재된-값이-상호-다른-경우">(3) 동일 국가이나 기재된 값이 상호 다른 경우</a></li>
    <li><a href="#4-corona-데이터-가공하기">(4) corona 데이터 가공하기</a></li>
    <li><a href="#5-241개의-행으로-맞추기">(5) 241개의 행으로 맞추기</a></li>
    <li><a href="#6-na값-처리하기">(6) NA값 처리하기</a></li>
    <li><a href="#7-데이터-저장">(7) 데이터 저장</a></li>
    <li><a href="#v-수강생을-위한-과제">V. 수강생을 위한 과제</a></li>
    <li><a href="#vi-결론">VI. 결론</a></li>
  </ul>
</nav>
	</div>
</div>
<div class="content post__content clearfix">
			<h2 id="공지">공지</h2>
<p>이번에 준비한 튜토리얼은 제 강의를 듣는 과거-현재-미래 수강생분들을 위해 준비한 자료이다. 많은 도움이 되기를 바란다</p>
<p>이번에 준비한 Tutorial 코로나 세계현황을 <code>Shiny Dashboard</code>로 만들어 가는 과정을 담았다.</p>
<h2 id="i-shiny-tutorial-소개">I. Shiny Tutorial 소개</h2>
<p>처음 shiny를 접하거나 shiny의 전체 튜토리얼이 궁금한 사람들을 위해 이전 글을 소개한다.</p>
<ul>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_01/">shiny tutorial 01 - get started</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_02/">shiny tutorial 02 - Shiny Structure</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_03/">shiny tutorial 03 - HTML content</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_04/">shiny tutorial 04 - Shiny Layouts</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_05/">shiny tutorial 05 - Sharing Apps</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_06/">shiny tutorial 06 - shinydashboard</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_07/">shiny tutorial 07 - flexdashboard</a></li>
<li><a href="https://chloevan.github.io/r/shiny/tutorial_08/">shiny tutorial 08 - HTML, CSS 적용</a></li>
</ul>
<h2 id="ii-shiny-project">II. Shiny Project</h2>
<p>현재 진행중인 프로젝트가 궁금하다면 아래를 확인해보자.</p>
<ul>
<li><a href="https://chloevan.github.io/r/shiny/project_01/">Corona Shiny Project 1 - Get Data</a></li>
<li><a href="https://chloevan.github.io/r/shiny/project_02/">Corona Shiny Project 2 - Visusalization (Time Series)</a></li>
<li><a href="https://chloevan.github.io/r/shiny/project_03/">Corona Shiny Project 3 - Visusalization (Bubble Chart)</a></li>
<li><a href="https://chloevan.github.io/r/shiny/project_04/">Corona Shiny Project 4 - Visusalization (Map Chart)</a></li>
<li><a href="https://chloevan.github.io/r/shiny/project_05/">Corona Shiny Project 5 - Chart with DateInput</a></li>
</ul>
<h2 id="iii-생각해볼-문제">III. 생각해볼 문제</h2>
<p>생각해볼 문제, <code>sliderInput</code>의 기능을 활용한다는 것의 의미는 매일매일 데이터가 변화하는 것을 확인하는 것에 의미가 있다. 누적데이터가 중요한지, 아니면 매일매일 업데이트된 데이터가 중요한지에 따라 대시보드의 성격이 달라진다.</p>
<p>우선, 누적데이터는 <code>line Graph</code>를 통해서 한번 보여줬기 때문에, 여기에서는 생략하겠다.</p>
<p>날짜가 변화할 때마다 국가별 <code>Case</code>가 달라지는 과정을 보여주고자 한다. 그런데, 문제가 있다.</p>
<h2 id="iv-데이터-처리의-문제점">IV. 데이터 처리의 문제점</h2>
<p>이 튜토리얼을 계속 따라왔다면, 다양한 데이터셋이 사용되고 있음을 알 수 있다.</p>
<ul>
<li><code>corona 데이터셋</code></li>
<li><code>지도 데이터셋</code></li>
</ul>
<p>지도 데이터셋은 <code>sp</code>라는 특별한 객체로 이루어져 있고, 이미 깔끔하게 국가별 지도 <code>mapping</code>까지 완료된 데이터셋이다.</p>
<p>그럼 여기에서 기준이 데이터셋이 무엇일까? 당연히 <code>지도 데이터셋</code>이다. 강사가 시간을 가장 많이 허비한 포인트가 이 지점이다. 이 글을 읽는 사람은 그러려니 하겠지만, 사실 매우 중요하다. 왜냐하면, 지도가 <code>Plotting</code> 되지 않는다!</p>
<h2 id="1-지도-데이터셋에-포함된-국가의-숫자">(1) 지도 데이터셋에 포함된 국가의 숫자</h2>
<p>우선 지도 데이터셋을 좀 더 면밀히 확인해보자.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(rgdal)
</code></pre></div><pre><code>## Loading required package: sp
</code></pre><pre><code>## rgdal: version: 1.4-8, (SVN revision 845)
##  Geospatial Data Abstraction Library extensions to R successfully loaded
##  Loaded GDAL runtime: GDAL 2.4.2, released 2019/06/28
##  Path to GDAL shared files: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgdal/gdal
##  GDAL binary built with GEOS: FALSE 
##  Loaded PROJ.4 runtime: Rel. 5.2.0, September 15th, 2018, [PJ_VERSION: 520]
##  Path to PROJ.4 shared files: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgdal/proj
##  Linking to sp version: 1.3-2
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">countries <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">readOGR</span>(dsn <span style="color:#f92672">=</span><span style="color:#e6db74">&#34;~/Desktop/ne_50m_admin_0_countries&#34;</span>,
                     layer <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;ne_50m_admin_0_countries&#34;</span>,
                     encoding <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;utf-8&#34;</span>,use_iconv <span style="color:#f92672">=</span> T,
                     verbose <span style="color:#f92672">=</span> <span style="color:#66d9ef">FALSE</span>)

<span style="color:#a6e22e">length</span>(<span style="color:#a6e22e">unique</span>(countries<span style="color:#f92672">$</span>NAME))
</code></pre></div><pre><code>## [1] 241
</code></pre><p>우선 241개로 확인이 된다.</p>
<h2 id="2-corona-데이터셋-국가의-숫자">(2) corona 데이터셋 국가의 숫자</h2>
<p>이번에는 다운로드 엑셀 파일을 Import 하여 실제 국가의 숫자가 몇개인지 확인해본다.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(readxl)
<span style="color:#a6e22e">library</span>(httr)

<span style="color:#75715e"># URL Copy</span>
url <span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#39;https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx&#39;</span>

<span style="color:#75715e"># 파일 이름만 가져오기</span>
getFileName <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">basename</span>(url)

<span style="color:#75715e"># 지정된 디렉토리에 파일 다운로드 받기</span>
<span style="color:#a6e22e">download.file</span>(url <span style="color:#f92672">=</span> url, destfile <span style="color:#f92672">=</span> getFileName)

<span style="color:#75715e"># 지정된 디렉토리에서 파일 업로드 하기</span>
corona <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read_excel</span>(getFileName)
<span style="color:#a6e22e">length</span>(<span style="color:#a6e22e">unique</span>(corona<span style="color:#f92672">$</span>countriesAndTerritories))
</code></pre></div><pre><code>## [1] 206
</code></pre><p>일단 <code>countries</code> 데이터셋의 국가의 숫자와 <code>corona</code> 데이터셋의 국가의 숫자가 다른 것이 눈에 띈다.</p>
<p>어떻게 해결 할 것인가? 하는 문제점이 발생한다.</p>
<h2 id="3-동일-국가이나-기재된-값이-상호-다른-경우">(3) 동일 국가이나 기재된 값이 상호 다른 경우</h2>
<p>우선 <code>U</code>로 시작하는 국가를 양쪽에서 추출한 후 비교해보자.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(dplyr)
</code></pre></div><pre><code>## 
## Attaching package: 'dplyr'
</code></pre><pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag
</code></pre><pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(stringr)
country_names <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.character</span>(countries<span style="color:#f92672">$</span>NAME)
corona_names <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.character</span>(<span style="color:#a6e22e">unique</span>(corona<span style="color:#f92672">$</span>countriesAndTerritories))

<span style="color:#a6e22e">print</span>(<span style="color:#a6e22e">data.frame</span>(
  from_countries <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(country_names<span style="color:#a6e22e">[str_detect</span>(country_names, pattern <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;^U&#34;</span>) <span style="color:#f92672">==</span> <span style="color:#66d9ef">TRUE</span>], <span style="color:#e6db74">&#34;empty&#34;</span>), 
  from_corona <span style="color:#f92672">=</span> corona_names<span style="color:#a6e22e">[str_detect</span>(corona_names, pattern <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;^U&#34;</span>) <span style="color:#f92672">==</span> <span style="color:#66d9ef">TRUE</span>]
))
</code></pre></div><pre><code>##             from_countries                  from_corona
## 1               Uzbekistan                       Uganda
## 2                  Uruguay                      Ukraine
## 3          U.S. Virgin Is.         United_Arab_Emirates
## 4 United States of America               United_Kingdom
## 5           United Kingdom  United_Republic_of_Tanzania
## 6     United Arab Emirates     United_States_of_America
## 7                  Ukraine United_States_Virgin_Islands
## 8                   Uganda                      Uruguay
## 9                    empty                   Uzbekistan
</code></pre><p>위 데이터에서 볼 수 있는 것처럼, 똑같은 미국이지만, 표기법이 다르다. (강사의 혼잣말, 고치는 방법이 있기는 하다. 그런데, 쉽지가 않다! 강의의 본질은 고생은 수강생이 하는게 아니라 원래 강의 준비하는 사람이 하는거다!)</p>
<p>우선 진행방법은 아래와 같다. 여기에서 국가명을 고쳐야 하는 건, <code>corona</code> 데이터셋이다.</p>
<p>수정하는 방법은 아래와 같다.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(dplyr)
<span style="color:#a6e22e">library</span>(stringr)

corona<span style="color:#f92672">$</span>countriesAndTerritories[corona<span style="color:#f92672">$</span>countriesAndTerritories <span style="color:#f92672">==</span><span style="color:#e6db74">&#34;United_Arab_Emirates&#34;</span>]<span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#34;United Arab Emirates&#34;</span>
corona<span style="color:#f92672">$</span>countriesAndTerritories[corona<span style="color:#f92672">$</span>countriesAndTerritories <span style="color:#f92672">==</span><span style="color:#e6db74">&#34;United_States_Virgin_Islands&#34;</span>]<span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#34;U.S. Virgin Is.&#34;</span>
corona<span style="color:#f92672">$</span>countriesAndTerritories[corona<span style="color:#f92672">$</span>countriesAndTerritories <span style="color:#f92672">==</span><span style="color:#e6db74">&#34;United_States_of_America&#34;</span>]<span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#34;United States of America&#34;</span>
corona<span style="color:#f92672">$</span>countriesAndTerritories[corona<span style="color:#f92672">$</span>countriesAndTerritories <span style="color:#f92672">==</span><span style="color:#e6db74">&#34;United_Republic_of_Tanzania&#34;</span>]<span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#34;empty&#34;</span>

country_names <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sort</span>(<span style="color:#a6e22e">as.character</span>(countries<span style="color:#f92672">$</span>NAME), decreasing <span style="color:#f92672">=</span> <span style="color:#66d9ef">TRUE</span>)
corona_names <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sort</span>(<span style="color:#a6e22e">as.character</span>(<span style="color:#a6e22e">unique</span>(corona<span style="color:#f92672">$</span>countriesAndTerritories)), decreasing <span style="color:#f92672">=</span> <span style="color:#66d9ef">TRUE</span>)

<span style="color:#a6e22e">print</span>(<span style="color:#a6e22e">data.frame</span>(
  from_countries <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(country_names<span style="color:#a6e22e">[str_detect</span>(country_names, pattern <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;^U&#34;</span>) <span style="color:#f92672">==</span> <span style="color:#66d9ef">TRUE</span>]), 
  from_corona <span style="color:#f92672">=</span> corona_names<span style="color:#a6e22e">[str_detect</span>(corona_names, pattern <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;^U&#34;</span>) <span style="color:#f92672">==</span> <span style="color:#66d9ef">TRUE</span>]
))
</code></pre></div><pre><code>##             from_countries              from_corona
## 1               Uzbekistan               Uzbekistan
## 2                  Uruguay                  Uruguay
## 3 United States of America           United_Kingdom
## 4           United Kingdom United States of America
## 5     United Arab Emirates     United Arab Emirates
## 6                  Ukraine                  Ukraine
## 7                   Uganda                   Uganda
## 8          U.S. Virgin Is.          U.S. Virgin Is.
</code></pre><p>위와 같은 방식으로 일일이 수정해야 한다! 갑자기 머리가 아파온다. 원래 데이터싸이언티스트는 <code>80%의 잡무</code>와 <code>20%의 우아함</code>으로 이루어진다고 한다. 이런일을 즐거워 해야 한다. 걱정마시라, 이미 데이터 전처리 된 데이터는 별도로 <code>URL</code>을 알려줄 것이다.</p>
<h2 id="4-corona-데이터-가공하기">(4) corona 데이터 가공하기</h2>
<p>여전히 한가지 더 큰 어려움이 있다. <code>241</code>개의 데이터셋을 맞춰야 한다. 그런데, <code>countries@data</code>의 행은 <code>241</code>개이지만, <code>corona</code>의 행은 <code>206</code>개이다. 어떻게 맞춰야 할까?</p>
<p>우선, corona데이터를 넓게 할 필요가 있다. 이유는 국가가 기준이기 때문이다. 즉, 국가가 첫번째 열에 오면 더 좋다.</p>
<p>이 때, 우리에게 필요한 지식은 <code>tidyr 패키지의 gather &amp; spread</code> 함수의 사용법이다. 자세한 설명이 필요하면 <a href="https://tidyr.tidyverse.org/">tidyr</a>에서 확인해보자.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(dplyr)
<span style="color:#a6e22e">library</span>(tidyr)

corona <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">select</span>(dateRep, countriesAndTerritories, cases) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e"># 필요한 열만 추출한다. </span>
  <span style="color:#a6e22e">group_by_at</span>(<span style="color:#a6e22e">vars</span>(<span style="color:#f92672">-</span>cases)) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e"># cases를 제외하고 모두 그룹을 한다는 뜻이다. </span>
  dplyr<span style="color:#f92672">::</span><span style="color:#a6e22e">mutate</span>(row_id<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#a6e22e">n</span>()) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">ungroup</span>() <span style="color:#f92672">%&gt;%</span>  <span style="color:#75715e"># 그룹 인덱스를 만든다.</span>
  <span style="color:#a6e22e">spread</span>(key<span style="color:#f92672">=</span>dateRep, value<span style="color:#f92672">=</span>cases) <span style="color:#f92672">%&gt;%</span> <span style="color:#75715e"># </span>
  <span style="color:#a6e22e">select</span>(<span style="color:#f92672">-</span>row_id) <span style="color:#f92672">-&gt;</span> dataCases <span style="color:#75715e"># 인덱스 제거 후 corona2로 저장한다. </span>

<span style="color:#a6e22e">glimpse</span>(dataCases)
</code></pre></div><pre><code>## Rows: 206
## Columns: 107
## $ countriesAndTerritories &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Andorra…
## $ `2019-12-31`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-01`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-02`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-03`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-04`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-05`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-06`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-07`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-08`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-09`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-10`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-11`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-12`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-13`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-14`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-15`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-16`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-17`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-18`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-19`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-20`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-21`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-22`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-23`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-24`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-25`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-01-26`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 3, 0, 0,…
## $ `2020-01-27`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-28`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-29`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-01-30`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 2, 0, 0,…
## $ `2020-01-31`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-01`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 2, 0, 0,…
## $ `2020-02-02`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 2, 0, 0,…
## $ `2020-02-03`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-04`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-05`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-06`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-07`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-08`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-09`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-10`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-11`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-12`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-13`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-14`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-15`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-16`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-17`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-18`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-19`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-20`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-21`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 2, 0, 0,…
## $ `2020-02-22`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 4, 0, 0,…
## $ `2020-02-23`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-24`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-25`            &lt;dbl&gt; 1, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 0, 0,…
## $ `2020-02-26`            &lt;dbl&gt; 0, NA, 1, NA, NA, NA, NA, NA, 0, NA, 0, 2, 0,…
## $ `2020-02-27`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 1, 0, 0,…
## $ `2020-02-28`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 0, 3, 0,…
## $ `2020-02-29`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 0, NA, 2, 2, 1,…
## $ `2020-03-01`            &lt;dbl&gt; 0, NA, 0, NA, NA, NA, NA, NA, 1, NA, 1, 3, 0,…
## $ `2020-03-02`            &lt;dbl&gt; 0, NA, 2, NA, NA, NA, NA, NA, 0, NA, 3, 4, 2,…
## $ `2020-03-03`            &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, 4, 4, …
## $ `2020-03-04`            &lt;dbl&gt; NA, NA, 2, NA, NA, NA, NA, 1, NA, NA, 8, 6, N…
## $ `2020-03-05`            &lt;dbl&gt; NA, NA, 7, NA, NA, NA, NA, NA, NA, NA, 11, 5,…
## $ `2020-03-06`            &lt;dbl&gt; NA, NA, 5, NA, NA, NA, NA, 1, NA, NA, 7, 12, …
## $ `2020-03-07`            &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, 6, NA, NA, 4, 33,…
## $ `2020-03-08`            &lt;dbl&gt; 3, NA, NA, NA, NA, NA, NA, 1, NA, NA, 11, 25,…
## $ `2020-03-09`            &lt;dbl&gt; NA, 2, 3, NA, NA, NA, NA, 3, NA, NA, 6, 3, NA…
## $ `2020-03-10`            &lt;dbl&gt; NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, 20, 29…
## $ `2020-03-11`            &lt;dbl&gt; 3, 4, NA, NA, NA, NA, NA, 7, NA, NA, 12, 51, …
## $ `2020-03-12`            &lt;dbl&gt; NA, 1, 0, NA, NA, NA, NA, NA, 3, NA, 14, 64, …
## $ `2020-03-13`            &lt;dbl&gt; NA, 12, 4, NA, NA, NA, NA, 12, 2, 2, 30, 115,…
## $ `2020-03-14`            &lt;dbl&gt; NA, 10, 2, 1, NA, NA, NA, 3, 7, NA, 41, 143, …
## $ `2020-03-15`            &lt;dbl&gt; 3, 5, 11, NA, NA, NA, 1, 11, 7, NA, 52, 151, …
## $ `2020-03-16`            &lt;dbl&gt; 6, 4, 11, 3, NA, NA, NA, 11, 10, NA, 49, 205,…
## $ `2020-03-17`            &lt;dbl&gt; 5, 9, 12, 9, NA, NA, NA, 9, 22, NA, 77, 156, …
## $ `2020-03-18`            &lt;dbl&gt; 1, 4, 0, 0, NA, NA, NA, 14, 26, NA, 79, 316, …
## $ `2020-03-19`            &lt;dbl&gt; 0, 4, 13, 39, NA, NA, NA, 18, 37, NA, 111, 31…
## $ `2020-03-20`            &lt;dbl&gt; 0, 11, 9, 22, NA, NA, NA, 31, 7, 2, 144, 550,…
## $ `2020-03-21`            &lt;dbl&gt; 2, 0, 12, 0, NA, NA, 0, 30, 14, NA, 165, 453,…
## $ `2020-03-22`            &lt;dbl&gt; 0, 6, 0, 13, 2, NA, 0, 67, 24, NA, 224, 375, …
## $ `2020-03-23`            &lt;dbl&gt; 10, 13, 8, 25, 0, NA, 0, 41, 30, NA, 611, 607…
## $ `2020-03-24`            &lt;dbl&gt; 6, 11, 87, 20, 0, NA, 0, 35, 4, 8, 114, 855, …
## $ `2020-03-25`            &lt;dbl&gt; 2, 23, 42, 31, 0, NA, 2, 86, 71, 5, 600, 796,…
## $ `2020-03-26`            &lt;dbl&gt; 33, 23, 33, 24, 0, NA, 0, 115, 25, 2, 376, 60…
## $ `2020-03-27`            &lt;dbl&gt; 0, 28, 41, 36, 1, 2, 4, 87, 39, 9, 367, 1141,…
## $ `2020-03-28`            &lt;dbl&gt; 16, 12, 0, 43, 1, 0, 0, 101, 43, 0, 212, 668,…
## $ `2020-03-29`            &lt;dbl&gt; 15, 11, 104, 41, 0, 0, 0, 55, 52, 0, 431, 594…
## $ `2020-03-30`            &lt;dbl&gt; 8, 15, 45, 26, 3, 0, 0, 75, 0, 22, 284, 522, …
## $ `2020-03-31`            &lt;dbl&gt; 27, 11, 57, 36, 0, 0, 0, 146, 58, NA, 464, 80…
## $ `2020-04-01`            &lt;dbl&gt; 25, 20, 73, 6, 0, 0, 0, 0, 50, 5, 150, 564, 2…
## $ `2020-04-02`            &lt;dbl&gt; 26, 16, 263, 14, 1, 0, 0, 167, 39, 0, 269, 52…
## $ `2020-04-03`            &lt;dbl&gt; 43, 18, 0, 38, 0, 1, 2, 0, 92, 5, 248, 418, 4…
## $ `2020-04-04`            &lt;dbl&gt; 0, 27, 139, 11, 0, 0, 6, 132, 73, 2, 324, 396…
## $ `2020-04-05`            &lt;dbl&gt; 35, 29, 314, 27, 2, 0, 0, 186, 34, 2, 139, 24…
## $ `2020-04-06`            &lt;dbl&gt; 29, 28, 20, 35, 4, 0, 0, 103, 52, 0, 57, 217,…
## $ `2020-04-07`            &lt;dbl&gt; 38, 16, 103, 25, 2, 0, 0, 74, 11, 7, 100, 314…
## $ `2020-04-08`            &lt;dbl&gt; 30, 6, 45, 19, 1, 0, 0, 87, 20, 3, 112, 343, …
## $ `2020-04-09`            &lt;dbl&gt; 56, 17, 104, 19, 2, 0, 0, 80, 28, 3, 96, 329,…
## $ `2020-04-10`            &lt;dbl&gt; 61, 9, 94, 19, 0, 0, 4, 99, 40, 5, 100, 279, …
## $ `2020-04-11`            &lt;dbl&gt; 37, 7, 95, 18, 0, 0, 2, 81, 16, 4, 86, 312, 6…
## $ `2020-04-12`            &lt;dbl&gt; 34, 17, 64, 21, 0, 0, 0, 162, 30, 6, 51, 247,…
## $ `2020-04-13`            &lt;dbl&gt; 52, 13, 89, 16, 0, 0, 0, 66, 46, 0, 33, 130, …
## $ `2020-04-14`            &lt;dbl&gt; 58, 21, 69, 8, 0, 0, 2, 69, 26, 0, 44, 106, 5…
</code></pre><h2 id="5-241개의-행으로-맞추기">(5) 241개의 행으로 맞추기</h2>
<p>이제 Table Join을 활용해야 한다. 이 때 조인키를 확인해야 한다. 그리고 countries 데이터셋에 맞추도록 한다.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">coronaConfirmed <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">left_join</span>(<span style="color:#a6e22e">data.frame</span>(countries <span style="color:#f92672">=</span> countries<span style="color:#f92672">$</span>NAME <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">as.character</span>(), 
                                   Pop <span style="color:#f92672">=</span> countries<span style="color:#f92672">$</span>POP_EST <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">as.character</span>() <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">as.numeric</span>()), 
                        dataCases <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">rename</span>(countries <span style="color:#f92672">=</span> countriesAndTerritories)) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">filter</span>(<span style="color:#f92672">!</span><span style="color:#a6e22e">is.na</span>(countries))
</code></pre></div><pre><code>## Joining, by = &quot;countries&quot;
</code></pre><pre><code>## Warning: Column `countries` joining factor and character vector, coercing into
## character vector
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">glimpse</span>(coronaConfirmed)
</code></pre></div><pre><code>## Rows: 241
## Columns: 108
## $ countries    &lt;chr&gt; &quot;Zimbabwe&quot;, &quot;Zambia&quot;, &quot;Yemen&quot;, &quot;Vietnam&quot;, &quot;Venezuela&quot;, &quot;…
## $ Pop          &lt;dbl&gt; 13805084, 15972000, 28036829, 96160163, 31304016, 1000, …
## $ `2019-12-31` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-01` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-02` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-03` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-04` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-05` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-06` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-07` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-08` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-09` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-10` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-11` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-12` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-13` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-14` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-15` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-16` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-17` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-18` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-19` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-20` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-21` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-22` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-23` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-24` &lt;dbl&gt; NA, NA, NA, 2, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-25` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-26` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-27` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-28` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-29` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-30` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-01-31` &lt;dbl&gt; NA, NA, NA, 3, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-01` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-02` &lt;dbl&gt; NA, NA, NA, 2, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-03` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-04` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-05` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-06` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-07` &lt;dbl&gt; NA, NA, NA, 2, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-08` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-09` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-10` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-11` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-12` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-13` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-14` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-15` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-16` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-17` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-18` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-19` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-20` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-21` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-22` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-23` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-24` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-25` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-26` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-27` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-28` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-02-29` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-01` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-02` &lt;dbl&gt; NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-03` &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ `2020-03-04` &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ `2020-03-05` &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ `2020-03-06` &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ `2020-03-07` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-08` &lt;dbl&gt; NA, NA, NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-09` &lt;dbl&gt; NA, NA, NA, 9, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-10` &lt;dbl&gt; NA, NA, NA, 1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-11` &lt;dbl&gt; NA, NA, NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-12` &lt;dbl&gt; NA, NA, NA, 4, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-13` &lt;dbl&gt; NA, NA, NA, 5, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-14` &lt;dbl&gt; NA, NA, NA, 5, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ `2020-03-15` &lt;dbl&gt; NA, NA, NA, 4, 10, NA, NA, NA, 6, NA, NA, NA, NA, NA, NA…
## $ `2020-03-16` &lt;dbl&gt; NA, NA, NA, 4, 5, NA, NA, 6, 2, NA, NA, NA, NA, NA, NA, …
## $ `2020-03-17` &lt;dbl&gt; NA, NA, NA, 4, 18, NA, NA, 2, 21, NA, NA, NA, NA, NA, NA…
## $ `2020-03-18` &lt;dbl&gt; NA, NA, NA, 0, 0, NA, NA, 8, 21, NA, NA, NA, NA, NA, NA,…
## $ `2020-03-19` &lt;dbl&gt; NA, 2, NA, 15, 0, NA, NA, 7, 29, NA, NA, NA, NA, 3, NA, …
## $ `2020-03-20` &lt;dbl&gt; NA, 0, NA, 9, 0, NA, NA, 0, 15, NA, NA, NA, NA, 9, NA, N…
## $ `2020-03-21` &lt;dbl&gt; 1, 0, NA, 2, 3, NA, NA, 10, 16, NA, NA, NA, NA, 2, NA, N…
## $ `2020-03-22` &lt;dbl&gt; 1, 0, NA, 7, 0, NA, NA, 0, 25, NA, NA, NA, NA, 1, NA, NA…
## $ `2020-03-23` &lt;dbl&gt; 0, 1, NA, 24, 0, NA, NA, 13, 23, NA, NA, NA, NA, 12, NA,…
## $ `2020-03-24` &lt;dbl&gt; 0, 0, NA, 5, 48, NA, NA, 3, 4, NA, NA, NA, 17, 2, NA, NA…
## $ `2020-03-25` &lt;dbl&gt; 0, 0, NA, 11, 7, NA, NA, 6, 27, NA, NA, NA, 0, 3, NA, NA…
## $ `2020-03-26` &lt;dbl&gt; 1, 9, NA, 14, 15, NA, NA, 10, 28, NA, NA, NA, 0, 5, NA, …
## $ `2020-03-27` &lt;dbl&gt; 0, 2, NA, 5, 1, NA, NA, 18, 21, NA, NA, NA, 0, 12, NA, N…
## $ `2020-03-28` &lt;dbl&gt; 2, 2, NA, 16, 12, NA, NA, 21, 0, NA, NA, NA, 2, 2, NA, N…
## $ `2020-03-29` &lt;dbl&gt; 2, 12, NA, 54, 0, NA, NA, 29, 66, NA, NA, NA, 3, 4, NA, …
## $ `2020-03-30` &lt;dbl&gt; 0, 1, NA, 5, 0, NA, NA, 12, 5, NA, NA, NA, 8, 1, NA, NA,…
## $ `2020-03-31` &lt;dbl&gt; 0, 6, NA, 1, 16, NA, NA, 4, 11, NA, NA, NA, NA, 4, NA, N…
## $ `2020-04-01` &lt;dbl&gt; 1, 0, NA, 0, 0, NA, NA, 24, 18, NA, NA, NA, 0, 9, NA, NA…
## $ `2020-04-02` &lt;dbl&gt; 0, 1, NA, 6, 8, NA, NA, 14, 0, NA, NA, NA, 0, 8, NA, NA,…
## $ `2020-04-03` &lt;dbl&gt; 0, 3, NA, 4, 1, NA, NA, 3, 31, NA, NA, NA, 3, 5, NA, NA,…
## $ `2020-04-04` &lt;dbl&gt; 1, 0, NA, 0, 0, NA, NA, 37, 17, NA, NA, NA, 7, 5, NA, NA…
## $ `2020-04-05` &lt;dbl&gt; 0, 0, NA, 1, 0, NA, NA, 39, 14, NA, NA, NA, 0, 6, NA, NA…
## $ `2020-04-06` &lt;dbl&gt; 0, 0, NA, 1, 4, NA, NA, 76, 6, NA, NA, NA, 2, 17, NA, NA…
## $ `2020-04-07` &lt;dbl&gt; 0, 0, NA, 4, 11, NA, NA, 55, 9, NA, NA, NA, 0, 2, NA, NA…
## $ `2020-04-08` &lt;dbl&gt; 1, 0, NA, 6, 7, NA, NA, 107, 9, NA, NA, NA, 3, 9, NA, NA…
## $ `2020-04-09` &lt;dbl&gt; 1, 0, NA, 0, 1, NA, NA, 51, 32, NA, NA, NA, 0, 4, NA, NA…
## $ `2020-04-10` &lt;dbl&gt; 0, 0, 1, 4, 4, NA, NA, 27, 17, NA, NA, NA, 5, 3, NA, NA,…
## $ `2020-04-11` &lt;dbl&gt; 0, 1, 0, 2, 4, NA, NA, 42, 21, NA, NA, NA, 0, 2, NA, NA,…
## $ `2020-04-12` &lt;dbl&gt; 3, 0, 0, 1, 0, NA, NA, 172, 7, NA, NA, NA, 1, 3, NA, NA,…
## $ `2020-04-13` &lt;dbl&gt; 0, 3, 0, 4, 6, NA, NA, 69, 11, NA, NA, NA, 0, 0, NA, NA,…
## $ `2020-04-14` &lt;dbl&gt; 3, 2, 0, 3, 8, NA, NA, 133, 9, NA, NA, NA, 0, 1, NA, NA,…
</code></pre><h2 id="6-na값-처리하기">(6) NA값 처리하기</h2>
<p>국가 및 날짜별로 <code>case</code>가 정리된 것을 확인할 수 있다. 아직 문제는 끝나지 않았다. 왜냐하면 <code>NA</code>가 있기 때문이다. <code>NA</code>가 포함된 부분은 모두 0으로 처리하자. 왜냐하면, 우리는 숫자로 표시해야 하기 때문에 <code>NA</code>의 공백은 있을 수 없다.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(ggplot2)

<span style="color:#a6e22e">sapply</span>(coronaConfirmed[<span style="color:#f92672">-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>)],<span style="color:#a6e22e">function</span>(x) <span style="color:#a6e22e">sum</span>(<span style="color:#a6e22e">is.na</span>(x))) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">as_tibble</span>() <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(date <span style="color:#f92672">=</span> <span style="color:#a6e22e">as.Date</span>(<span style="color:#a6e22e">colnames</span>(coronaConfirmed)[<span style="color:#f92672">-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>)])) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">ggplot</span>(<span style="color:#a6e22e">aes</span>(x <span style="color:#f92672">=</span> date, y <span style="color:#f92672">=</span> value)) <span style="color:#f92672">+</span> 
    <span style="color:#a6e22e">geom_line</span>(size <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.5</span>, color <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;darkblue&#34;</span>) <span style="color:#f92672">+</span> 
    <span style="color:#a6e22e">theme_minimal</span>()
</code></pre></div><p><img src="/img/shiny/coronaProject/project_06/project_01.png" alt=""><!-- raw HTML omitted --></p>
<p><code>NA</code>값 처리에 관한 그래프를 작성한 것이다. 거의 모든 국가에서 발현되기 시작한 3월 이후부터는 <code>NA</code>가 줄어드는 것을 확인할 수 있다. (아! 시각화 분석이 아니다! 빨리 돌아가서 NA를 처리하자)</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">coronaConfirmed<span style="color:#a6e22e">[is.na</span>(coronaConfirmed)] <span style="color:#f92672">&lt;-</span> <span style="color:#ae81ff">0</span>
<span style="color:#a6e22e">sapply</span>(coronaConfirmed[<span style="color:#f92672">-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>)],<span style="color:#a6e22e">function</span>(x) <span style="color:#a6e22e">sum</span>(<span style="color:#a6e22e">is.na</span>(x))) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">as_tibble</span>() <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">mutate</span>(date <span style="color:#f92672">=</span> <span style="color:#a6e22e">as.Date</span>(<span style="color:#a6e22e">colnames</span>(coronaConfirmed)[<span style="color:#f92672">-</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>)])) <span style="color:#f92672">%&gt;%</span> 
  <span style="color:#a6e22e">ggplot</span>(<span style="color:#a6e22e">aes</span>(x <span style="color:#f92672">=</span> date, y <span style="color:#f92672">=</span> value)) <span style="color:#f92672">+</span> 
    <span style="color:#a6e22e">geom_line</span>(size <span style="color:#f92672">=</span> <span style="color:#ae81ff">1.5</span>, color <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;darkblue&#34;</span>) <span style="color:#f92672">+</span> 
    <span style="color:#a6e22e">theme_minimal</span>()
</code></pre></div><p><img src="/img/shiny/coronaProject/project_06/project_02.png" alt=""><!-- raw HTML omitted --></p>
<p>모든 <code>NA</code>가 0으로 수렴되는 것을 볼 수 있다.</p>
<h2 id="7-데이터-저장">(7) 데이터 저장</h2>
<p>이렇게 전처리된 데이터를 다시 사용하기 위해, <code>csv</code>, <code>Database</code> 등 다양한 형태로 저장을 해본다. 이 부분은 수강생의 자율에 맡기도록 한다.</p>
<h2 id="v-수강생을-위한-과제">V. 수강생을 위한 과제</h2>
<p>지금까지 한것은 확진자(casesConfirmed) 데이터를 가지고 전처리를 진행하였다. 그러나, 확진후 사망자 수 데이터도 중요하며, 더 나아가 인구대비 확진자, 사망자 등도 중요한 데이터가 될 수 있다.</p>
<p>문제는 아직 사망자 수 데이터를 기반으로 작업은 하지 못했다는 점이다. 이 부분은 수강생을 위한 과제로 남겨두겠다.</p>
<h2 id="vi-결론">VI. 결론</h2>
<p>이번에는 데이터 전처리에 대해 배우는 시간을 가졌다. 이렇게 데이터 전처리는 어렵다. 강사 역시, 글을 쓰면서 하루의 시간을 모두 통으로 보내며 전처리의 과정을 진행했다. 단순히 소스코드를 짜는 것 뿐만 아니라, 하나씩 확인하는 과정, 좀 더 나은 방법들을 고민하면서 소스코드를 짜는데 주력하였다.</p>
<p>이제 마지막 <code>Chart Automation</code>만 남았다.</p>
<p>이글을 읽는 사람들에게 작게나마 도움이 되기를 바란다.</p>
<p><code>Pray for Victims of Covid_19. Contribution to them with this tutorial.</code></p>

		</div>
		<footer class="post__footer">
			
<div class="post__tags tags clearfix">
	<svg class="tags__badge icon icon-tag" width="16" height="16" viewBox="0 0 32 32"><path d="M32 19c0 1-1 2-1 2L21 31s-1 1-2 1-2-1-2-1L2 16c-1-1-1.4-2-1.4-2S0 12.5 0 11V3C0 1.5.8.8.8.8S1.5 0 3 0h8c1.5 0 3 .6 3 .6S15 1 16 2l15 15s1 1 1 2zM7 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/></svg>
	<ul class="tags__list">
		<li class="tags__item"><a class="tags__link btn" href="/tags/development/" rel="tag">Development</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/r/" rel="tag">R</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/shiny/" rel="tag">Shiny</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/shiny-dashboard/" rel="tag">Shiny Dashboard</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/shiny-project/" rel="tag">Shiny Project</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/corona/" rel="tag">Corona</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/leaflet/" rel="tag">leaflet</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/map-chart/" rel="tag">Map Chart</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/reactivity/" rel="tag">reactivity</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/%EC%BD%94%EB%A1%9C%EB%82%98-%EB%8C%80%EC%8B%9C%EB%B3%B4%EB%93%9C/" rel="tag">코로나 대시보드</a></li>
		<li class="tags__item"><a class="tags__link btn" href="/tags/corona-dashboard/" rel="tag">Corona Dashboard</a></li>
	</ul>
</div>
		</footer>
	</article>
</main>

<div class="authorbox clearfix">
	<figure class="authorbox__avatar">
		<img alt="ChloeEvan avatar" src="/img/couple.jpg" class="avatar" height="90" width="90">
	</figure>
	<div class="authorbox__header">
		<span class="authorbox__name">About ChloeEvan</span>
	</div>
	<div class="authorbox__description">
		ChloEvan is just one who are loving Chloe &amp; Evan and analyzing Data things. ChloeEvan&#39;s dream is to make the world better through loving Chloe &amp; Evan and working with Data
	</div>
</div>

<nav class="post-nav flex">
	<div class="post-nav__item post-nav__item--prev">
		<a class="post-nav__link" href="/r/newpkgs/gt_intro/" rel="prev"><span class="post-nav__caption">«&thinsp;Previous</span><p class="post-nav__post-title">GT 패키지 소개</p></a>
	</div>
	<div class="post-nav__item post-nav__item--next">
		<a class="post-nav__link" href="/r/basics/round/" rel="next"><span class="post-nav__caption">Next&thinsp;»</span><p class="post-nav__post-title">Round 함수 - digits</p></a>
	</div>
</nav>

<section class="comments">
	<div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "https-chloevan-github-io" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>


			</div>
			<aside class="sidebar"><div class="widget-search widget">
	<form class="widget-search__form" role="search" method="get" action="https://google.com/search">
		<label>
			<input class="widget-search__field" type="search" placeholder="SEARCH..." value="" name="q" aria-label="SEARCH...">
		</label>
		<input class="widget-search__submit" type="submit" value="Search">
		<input type="hidden" name="sitesearch" value="https://chloevan.github.io/" />
	</form>
</div>
<div class="widget-recent widget">
	<h4 class="widget__title">Recent Posts</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item"><a class="widget__link" href="/settings/colab_package_settings/">Python Package Settings on Google Colab</a></li>
			<li class="widget__item"><a class="widget__link" href="/gcp/bigquery/02_basics/ch17_types_of_functions/">Ch17 Types of Functions</a></li>
			<li class="widget__item"><a class="widget__link" href="/kaggle/competition_m5_eda_1/">competition - M5 EDA</a></li>
			<li class="widget__item"><a class="widget__link" href="/gcp/bigquery/02_basics/ch16_data_types_numeric_types/">Ch16 Data Types - Numeric types</a></li>
			<li class="widget__item"><a class="widget__link" href="/settings/kaggle_with_colab/">Kaggle with Google Colab</a></li>
		</ul>
	</div>
</div>
<div class="widget-categories widget">
	<h4 class="widget__title">Categories</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item">
				<a class="widget__link" href="/categories/bar-chart/">bar chart</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/basics/">Basics</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/bigquery/">BigQuery</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/bupar/">bupaR</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/corona-shiny-app/">Corona Shiny App</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-analysis/">Data Analysis</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-handling/">Data Handling</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-science-project/">Data Science Project</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-transformation/">Data Transformation</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-visualisation/">Data Visualisation</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/data-visualization/">Data Visualization</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/deep-learning/">Deep Learning</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/deployment/">Deployment</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/development/">Development</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/dplyr/">dplyr</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/ggplot2/">ggplot2</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/github/">Github</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/google-cloud/">Google Cloud</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/google-colab/">Google Colab</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/histogram/">Histogram</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/hugo/">Hugo</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/interactive-graph/">Interactive Graph</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/kaggle/">Kaggle</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/line-grpah/">line grpah</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/machine-learning/">Machine Learning</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/mathjax/">MathJax</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/matplotlib/">Matplotlib</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/missing-values/">Missing Values</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/new-packages/">New Packages</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/pandas/">Pandas</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/pie-plot/">Pie Plot</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/pivot-table/">pivot table</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/process-mining/">Process Mining</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/project/">Project</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/python/">Python</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/python-basic/">Python Basic</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/r/">R</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/r-markdown/">R Markdown</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/r-%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4/">R 마크다운</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/regular-expression/">regular expression</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/rpa/">RPA</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/scatter-plot/">Scatter Plot</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/settings/">Settings</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/shiny/">Shiny</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/statistics/">Statistics</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/supervised-learning/">Supervised Learning</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/table-chart/">Table Chart</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/tensorflow-2.0/">Tensorflow 2.0</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/tensorflow-2.0-tutorial/">Tensorflow 2.0 Tutorial</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/tutorial/">Tutorial</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/vcrs/">vcrs</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EA%B5%AC%EA%B8%80-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C/">구글 클라우드</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EA%B8%B0%EC%B4%88%ED%86%B5%EA%B3%84/">기초통계</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B6%84%EC%84%9D/">데이터 분석</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%9C%EA%B0%81%ED%99%94/">데이터 시각화</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%B8%EC%9D%B4%EC%96%B8%EC%8A%A4-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/">데이터 싸이언스 프로젝트</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EC%B2%98%EB%A6%AC/">데이터 전처리</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%94%A5%EB%9F%AC%EB%8B%9D/">딥러닝</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%A7%89%EB%8C%80-%EA%B7%B8%EB%9E%98%ED%94%84/">막대 그래프</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/">머신러닝</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%B3%B4%EA%B3%A0%EC%84%9C-%EC%9E%90%EB%8F%99%ED%99%94/">보고서 자동화</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EB%B9%85%EC%BF%BC%EB%A6%AC/">빅쿼리</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EC%84%A0-%EA%B7%B8%EB%9E%98%ED%94%84/">선 그래프</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D/">정규표현식</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-2.0/">텐서플로 2.0</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-2.0-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC/">텐서플로 2.0 튜토리얼</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EB%B6%84%EC%84%9D/">프로세스 분석</a>
			</li>
			<li class="widget__item">
				<a class="widget__link" href="/categories/%ED%94%BC%EB%B2%97-%ED%85%8C%EC%9D%B4%EB%B8%94/">피벗 테이블</a>
			</li>
		</ul>
	</div>
</div>
<div class="widget-taglist widget">
	<h4 class="widget__title">Tags</h4>
	<div class="widget__content">
		<a class="widget-taglist__link widget__link btn" href="/tags/across-datasets/" title="Across Datasets">Across Datasets</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/aggregates/" title="Aggregates">Aggregates</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/and-network/" title="AND Network">AND Network</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/append/" title="append">append</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/apply/" title="Apply">Apply</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/area-plot/" title="Area Plot">Area Plot</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/array_agg/" title="ARRAY_AGG">ARRAY_AGG</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/auto-encoder/" title="Auto Encoder">Auto Encoder</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bar-chart/" title="bar chart">bar chart</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/basics/" title="Basics">Basics</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bigquery/" title="BigQuery">BigQuery</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bigquery-with-python/" title="BigQuery with Python">BigQuery with Python</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bigquery-with-r/" title="BigQuery with R">BigQuery with R</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/binary-classification/" title="Binary Classification">Binary Classification</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/broadcasting/" title="Broadcasting">Broadcasting</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bubble-chart/" title="Bubble Chart">Bubble Chart</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/bupar/" title="bupaR">bupaR</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/classification/" title="Classification">Classification</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/clustering/" title="Clustering">Clustering</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/cnn/" title="CNN">CNN</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/combining-vectors/" title="Combining Vectors">Combining Vectors</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/convolutional-neural-network/" title="Convolutional Neural Network">Convolutional Neural Network</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/corona/" title="Corona">Corona</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/corona-dashboard/" title="Corona Dashboard">Corona Dashboard</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/cross-join/" title="Cross Join">Cross Join</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/css/" title="CSS">CSS</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/dashboard/" title="Dashboard">Dashboard</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-analysis/" title="Data Analysis">Data Analysis</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-handling/" title="Data Handling">Data Handling</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-transformation/" title="Data Transformation">Data Transformation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-types/" title="Data Types">Data Types</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-visualisation/" title="Data Visualisation">Data Visualisation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/data-visualization/" title="Data Visualization">Data Visualization</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/dataframe/" title="DataFrame">DataFrame</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/deep-learning/" title="Deep Learning">Deep Learning</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/deep-learning-linear-regression/" title="Deep Learning Linear Regression">Deep Learning Linear Regression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/deployment/" title="Deployment">Deployment</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/development/" title="Development">Development</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/distinct/" title="Distinct">Distinct</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/dplyr/" title="dplyr">dplyr</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/enumerate/" title="enumerate">enumerate</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/extend/" title="extend">extend</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/fashion-mnist/" title="Fashion MNIST">Fashion MNIST</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/filter/" title="filter">filter</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/for-loop/" title="for-loop">for-loop</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/gghistostats/" title="gghistostats">gghistostats</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/ggplot2/" title="ggplot2">ggplot2</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/github/" title="Github">Github</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/google-cloud/" title="Google Cloud">Google Cloud</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/google-colab/" title="Google Colab">Google Colab</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/group-by/" title="Group By">Group By</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/gru/" title="GRU">GRU</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/gru-%EB%A0%88%EC%9D%B4%EC%96%B4/" title="GRU 레이어">GRU 레이어</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/gt/" title="gt">gt</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/having/" title="Having">Having</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/histogram/" title="Histogram">Histogram</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/html5/" title="HTML5">HTML5</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/hugo/" title="Hugo">Hugo</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/image-augmentation/" title="Image Augmentation">Image Augmentation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/image-segmentation/" title="Image Segmentation">Image Segmentation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/image-settings/" title="Image Settings">Image Settings</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/indexing/" title="Indexing">Indexing</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/insert/" title="insert">insert</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/interactive-graph/" title="Interactive Graph">Interactive Graph</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/interview/" title="Interview">Interview</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/iterrows/" title="iterrows">iterrows</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/itertuples/" title="Itertuples">Itertuples</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/join/" title="JOIN">JOIN</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/jupyter-notebook/" title="Jupyter Notebook">Jupyter Notebook</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/kaggle/" title="Kaggle">Kaggle</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/lambda/" title="lambda">lambda</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/leaflet/" title="leaflet">leaflet</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/line-grpah/" title="line grpah">line grpah</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/linear-regression/" title="Linear Regression">Linear Regression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/list/" title="list">list</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/lists/" title="lists">lists</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/lstm/" title="LSTM">LSTM</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/m5-forecasting/" title="M5 Forecasting">M5 Forecasting</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/machine-learning/" title="Machine Learning">Machine Learning</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/map-chart/" title="Map Chart">Map Chart</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/mathjax-settings/" title="Mathjax Settings">Mathjax Settings</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/mathjax-%EC%84%A4%EC%A0%95/" title="Mathjax 설정">Mathjax 설정</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/matplotlib/" title="Matplotlib">Matplotlib</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/missing-values/" title="Missing Values">Missing Values</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/modeling-visualisation/" title="Modeling Visualisation">Modeling Visualisation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/multiple-linear-regression/" title="Multiple Linear Regression">Multiple Linear Regression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/multiprocessing/" title="multiprocessing">multiprocessing</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/natural-language-generation/" title="Natural Language Generation">Natural Language Generation</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/new-packages/" title="New Packages">New Packages</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/numpy/" title="NumPy">NumPy</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/or-network/" title="OR Network">OR Network</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/outer-join/" title="Outer Join">Outer Join</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pandas/" title="Pandas">Pandas</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pandas-dataframe/" title="Pandas Dataframe">Pandas Dataframe</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pandas-excel/" title="Pandas Excel">Pandas Excel</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pie-plot/" title="Pie Plot">Pie Plot</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/pivot-table/" title="pivot table">pivot table</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/plotly/" title="plotly">plotly</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/polar-chart/" title="Polar Chart">Polar Chart</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/process-analysis/" title="Process Analysis">Process Analysis</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/productive-box/" title="productive-box">productive-box</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/python/" title="Python">Python</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/python-basic/" title="Python Basic">Python Basic</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/python-excel/" title="Python Excel">Python Excel</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/python-%ED%8F%AC%ED%8A%B8%ED%8F%B4%EB%A6%AC%EC%98%A4/" title="Python 포트폴리오">Python 포트폴리오</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/r/" title="R">R</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/r-markdown/" title="R Markdown">R Markdown</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/r-%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4/" title="R 마크다운">R 마크다운</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/r-%ED%8F%AC%ED%8A%B8%ED%8F%B4%EB%A6%AC%EC%98%A4/" title="R 포트폴리오">R 포트폴리오</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/random-signoid/" title="Random Signoid">Random Signoid</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/random-signoid-bias/" title="Random Signoid Bias">Random Signoid Bias</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/reactivity/" title="reactivity">reactivity</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/recurrent-neural-network/" title="Recurrent Neural Network">Recurrent Neural Network</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/regression/" title="Regression">Regression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/regular-expression/" title="regular expression">regular expression</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/rnn/" title="RNN">RNN</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/round/" title="Round">Round</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/rpa/" title="RPA">RPA</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/scatter-plot/" title="Scatter Plot">Scatter Plot</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/sentiment-analysis/" title="Sentiment Analysis">Sentiment Analysis</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/settings/" title="Settings">Settings</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny/" title="Shiny">Shiny</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-app-%EB%B0%B0%ED%8F%AC/" title="Shiny App 배포">Shiny App 배포</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-dashboard/" title="Shiny Dashboard">Shiny Dashboard</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-deployment/" title="Shiny Deployment">Shiny Deployment</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-html/" title="Shiny HTML">Shiny HTML</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-layout/" title="Shiny Layout">Shiny Layout</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shiny-project/" title="Shiny Project">Shiny Project</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/shinydashboard/" title="shinydashboard">shinydashboard</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/simplernn/" title="SimpleRNN">SimpleRNN</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/sort_values/" title="sort_values">sort_values</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/split/" title="SPLIT">SPLIT</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/stacked-plot/" title="Stacked Plot">Stacked Plot</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/statistics/" title="Statistics">Statistics</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/struct/" title="STRUCT">STRUCT</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/subquery/" title="SubQuery">SubQuery</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/super-resolution/" title="Super Resolution">Super Resolution</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/swifter/" title="swifter">swifter</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/table-chart/" title="Table Chart">Table Chart</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/table-handling/" title="Table Handling">Table Handling</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/tensorflow-2.0/" title="Tensorflow 2.0">Tensorflow 2.0</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/tensorflow-2.0-tutorial/" title="Tensorflow 2.0 Tutorial">Tensorflow 2.0 Tutorial</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/tensorflow-for-r/" title="Tensorflow for R">Tensorflow for R</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/transfer-learning/" title="Transfer Learning">Transfer Learning</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/tutorial/" title="Tutorial">Tutorial</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/types-of-functions/" title="Types of Functions">Types of Functions</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/unnest/" title="UNNEST">UNNEST</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/vcrs/" title="vcrs">vcrs</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/vector/" title="Vector">Vector</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/vs-code/" title="VS Code">VS Code</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/xor-network/" title="XOR Network">XOR Network</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EA%B5%AC%EA%B8%80-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C/" title="구글 클라우드">구글 클라우드</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EA%B8%8D%EC%A0%95-%EB%B6%80%EC%A0%95-%EA%B0%90%EC%84%B1%EB%B6%84%EC%84%9D/" title="긍정, 부정 감성분석">긍정, 부정 감성분석</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EA%B8%B0%EC%B4%88%ED%86%B5%EA%B3%84/" title="기초통계">기초통계</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EA%B9%83%ED%97%88%EB%B8%8C/" title="깃허브">깃허브</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EA%B9%83%ED%97%88%EB%B8%8C-%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95/" title="깃허브 환경설정">깃허브 환경설정</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8B%A4%ED%95%AD%EB%B6%84%EB%A5%98/" title="다항분류">다항분류</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8B%A4%ED%95%AD%ED%9A%8C%EA%B7%80/" title="다항회귀">다항회귀</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8C%80%EC%8B%9C%EB%B3%B4%EB%93%9C/" title="대시보드">대시보드</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%9C%EA%B0%81%ED%99%94/" title="데이터 시각화">데이터 시각화</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%8B%B8%EC%9D%B4%EC%96%B8%EC%8A%A4-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/" title="데이터 싸이언스 프로젝트">데이터 싸이언스 프로젝트</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EC%B2%98%EB%A6%AC/" title="데이터 전처리">데이터 전처리</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%A7%89%EB%8C%80-%EA%B7%B8%EB%9E%98%ED%94%84/" title="막대 그래프">막대 그래프</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%AA%A8%EB%8D%B8%EB%A7%81-%EC%8B%9C%EA%B0%81%ED%99%94/" title="모델링 시각화">모델링 시각화</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B3%B4%EC%8A%A4%ED%84%B4-%EC%A3%BC%ED%83%9D-%EA%B0%80%EA%B2%A9-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%84%B8%ED%8A%B8/" title="보스턴 주택 가격 데이터세트">보스턴 주택 가격 데이터세트</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B6%84%EB%A5%98/" title="분류">분류</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B9%85%EC%BF%BC%EB%A6%AC/" title="빅쿼리">빅쿼리</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B9%85%EC%BF%BC%EB%A6%AC-r/" title="빅쿼리 R">빅쿼리 R</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B9%85%EC%BF%BC%EB%A6%AC-%EA%B8%B0%EB%B3%B8/" title="빅쿼리 기본">빅쿼리 기본</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EB%B9%85%EC%BF%BC%EB%A6%AC-%ED%8C%8C%EC%9D%B4%EC%8D%AC/" title="빅쿼리 파이썬">빅쿼리 파이썬</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%82%B0%EC%A0%90%EB%8F%84/" title="산점도">산점도</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%83%A4%EC%9D%B4%EB%8B%88-%EC%95%B1-%EB%B0%B0%ED%8F%AC/" title="샤이니 앱 배포">샤이니 앱 배포</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%84%A0-%EA%B7%B8%EB%9E%98%ED%94%84/" title="선 그래프">선 그래프</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80/" title="선형회귀">선형회귀</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%88%9C%ED%99%98-%EC%8B%A0%EA%B2%BD%EB%A7%9D/" title="순환 신경망">순환 신경망</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%8B%9C%EA%B0%81%ED%99%94-%EB%AC%B8%EB%B2%95/" title="시각화 문법">시각화 문법</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%8B%9C%EA%B7%B8%EB%85%B8%EC%9D%B4%EB%93%9C/" title="시그노이드">시그노이드</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%8B%A0%EA%B2%BD-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%A0%84%EC%9D%B4/" title="신경 스타일 전이">신경 스타일 전이</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%98%A4%ED%86%A0%EC%9D%B8%EC%BD%94%EB%8D%94/" title="오토인코더">오토인코더</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%B6%84%ED%95%A0/" title="이미지 분할">이미지 분할</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%84%A4%EC%A0%95/" title="이미지 설정">이미지 설정</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%9D%B4%ED%95%AD%EB%B6%84%EB%A5%98/" title="이항분류">이항분류</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%9E%84%EB%B2%A0%EB%94%A9-%EB%A0%88%EC%9D%B4%EC%96%B4/" title="임베딩 레이어">임베딩 레이어</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%9E%90%EC%97%B0%EC%96%B4-%EC%83%9D%EC%84%B1/" title="자연어 생성">자연어 생성</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%A0%84%EC%9D%B4-%ED%95%99%EC%8A%B5/" title="전이 학습">전이 학습</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D/" title="정규표현식">정규표현식</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%A7%80%EB%8F%84%ED%95%99%EC%8A%B5/" title="지도학습">지도학습</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%B4%88%ED%95%B4%EC%83%81%EB%8F%84/" title="초해상도">초해상도</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%BB%A8%EB%B3%BC%EB%A3%A8%EC%85%98-%EC%8B%A0%EA%B2%BD%EB%A7%9D/" title="컨볼루션 신경망">컨볼루션 신경망</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%EC%BD%94%EB%A1%9C%EB%82%98-%EB%8C%80%EC%8B%9C%EB%B3%B4%EB%93%9C/" title="코로나 대시보드">코로나 대시보드</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%85%8C%EC%9D%B4%EB%B8%94-%EB%8B%A4%EB%A3%A8%EA%B8%B0/" title="테이블 다루기">테이블 다루기</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-2.0/" title="텐서플로 2.0">텐서플로 2.0</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-2.0-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC/" title="텐서플로 2.0 튜토리얼">텐서플로 2.0 튜토리얼</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-%ED%97%88%EB%B8%8C/" title="텐서플로 허브">텐서플로 허브</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%8C%90%EB%8B%A4%EC%8A%A4-%EC%97%91%EC%85%80/" title="판다스 엑셀">판다스 엑셀</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%8C%90%EB%8B%A4%EC%8A%A4-%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0/" title="판다스 자료구조">판다스 자료구조</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%8F%AC%ED%8A%B8%ED%8F%B4%EB%A6%AC%EC%98%A4/" title="포트폴리오">포트폴리오</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EB%A7%88%EC%9D%B4%EB%8B%9D/" title="프로세스 마이닝">프로세스 마이닝</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EB%B6%84%EC%84%9D/" title="프로세스 분석">프로세스 분석</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%94%BC%EB%B2%97-%ED%85%8C%EC%9D%B4%EB%B8%94/" title="피벗 테이블">피벗 테이블</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%95%9C%EA%B8%80-%ED%8F%B0%ED%8A%B8-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0/" title="한글 폰트 오류 해결">한글 폰트 오류 해결</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95/" title="환경설정">환경설정</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%9A%8C%EA%B7%80%EB%AA%A8%ED%98%95/" title="회귀모형">회귀모형</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%9C%B4%EA%B3%A0/" title="휴고">휴고</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/%ED%9E%88%EC%8A%A4%ED%86%A0%EA%B7%B8%EB%9E%A8/" title="히스토그램">히스토그램</a>
	</div>
</div>
</aside>
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2020 ChloEvan.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
	</div>
<script async defer src="/js/menu.js"></script>
<script src="/js/custom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML" async>
MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [['$','$'], ['\\(','\\)']],
      displayMath: [['$$','$$']],
      processEscapes: true,
      processEnvironments: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
      TeX: { equationNumbers: { autoNumber: "AMS" },
           extensions: ["AMSmath.js", "AMSsymbols.js"] }
    }
    });
    MathJax.Hub.Queue(function() {
      
      
      
      var all = MathJax.Hub.getAllJax(), i;
      for(i = 0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
      }
    });
  
    MathJax.Hub.Config({
    
    TeX: { equationNumbers: { autoNumber: "AMS" } }
    });
</script>
</body>
</html>